# Степенной метод. Метод скалярных произведений

In [5]:
import numpy as np
from math import sqrt
import sys
from scipy.linalg import hilbert
from tabulate import tabulate

# В качестве тестовых данных используются

In [17]:
# 1. Матрица Гильберта пятого порядка
matrixHilbert5 = np.array(hilbert(5))
print('\n'.join(' '.join(str(cell) for cell in row) for row in matrixHilbert5))
print()


# 2. Матрица Гильберта шестого порядка
matrixHilbert6 = np.array(hilbert(6))
print('\n'.join(' '.join(str(cell) for cell in row) for row in matrixHilbert6))
print()

1.0 0.5 0.3333333333333333 0.25 0.2
0.5 0.3333333333333333 0.25 0.2 0.16666666666666666
0.3333333333333333 0.25 0.2 0.16666666666666666 0.14285714285714285
0.25 0.2 0.16666666666666666 0.14285714285714285 0.125
0.2 0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111

1.0 0.5 0.3333333333333333 0.25 0.2 0.16666666666666666
0.5 0.3333333333333333 0.25 0.2 0.16666666666666666 0.14285714285714285
0.3333333333333333 0.25 0.2 0.16666666666666666 0.14285714285714285 0.125
0.25 0.2 0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111
0.2 0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111 0.1
0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111 0.1 0.09090909090909091



### Степеной метод

In [11]:
def powerMethod(A, eps):
    x0 = np.array(np.ones(A.shape[0]))
    lamb = 0
    iteration = 0
    while True:
        iteration += 1
        x1 = np.dot(A, x0)
        if abs(x1[0] / x0[0] - lamb) < eps:
            lamb = x1[0] / x0[0]
            break
        lamb = x1[0] / x0[0]
        x0 = x1
    return lamb, iteration

### Метод скалярных произведений

In [12]:
def scalMethod(matrixHilbert5, eps):
    x0 = np.array(np.ones(matrixHilbert5.shape[0]))
    y0 = np.array(np.ones(matrixHilbert5.shape[0]))
    lamb = 0
    iteration = 0
    while True:
        iteration += 1
        x1 = np.dot(matrixHilbert5, x0)
        y1 = np.dot(matrixHilbert5.T, y0)
        if abs(np.dot(x1, y1) / np.dot(x0, y1) - lamb) < eps:
            lamb = np.dot(x1, y1) / np.dot(x0, y1)
            break
        lamb = np.dot(x1, y1) / np.dot(x0, y1)
        x0 = x1
        y0 = y1
    return lamb, iteration

### Вывод данных (Матрица Гильберта пятого порядка)

In [30]:
print("Матрица Гильберта пятого порядка:")
print(*matrixHilbert5, sep='\n')
print()
lambdaAcc = max(abs(np.linalg.eig(matrixHilbert5)[0]))
for eps in (1e-2, 1e-3, 1e-4, 1e-5):
    print("Погрешность:", eps)
    print("Степенной метод:")
    print("    Количество итераций:", powerMethod(matrixHilbert5, eps)[1])
    print("    |lambdaAcc - lambda|:", abs(lambdaAcc - abs(powerMethod(matrixHilbert5, eps)[0])))
    print()
    print("Метод скалярных произведений:")
    print("    Количество итераций:", scalMethod(A, eps)[1])
    print("    |lambdaAcc - lambda|:", abs(lambdaAcc - abs(scalMethod(matrixHilbert5, eps)[0])))
    print()
    print()
    print()

Матрица Гильберта пятого порядка:
[1.         0.5        0.33333333 0.25       0.2       ]
[0.5        0.33333333 0.25       0.2        0.16666667]
[0.33333333 0.25       0.2        0.16666667 0.14285714]
[0.25       0.2        0.16666667 0.14285714 0.125     ]
[0.2        0.16666667 0.14285714 0.125      0.11111111]

Погрешность: 0.01
Степенной метод:
    Количество итераций: 4
    |lambdaAcc - lambda|: 0.001221369082482049

Метод скалярных произведений:
    Количество итераций: 3
    |lambdaAcc - lambda|: 1.3406487585410076e-05



Погрешность: 0.001
Степенной метод:
    Количество итераций: 6
    |lambdaAcc - lambda|: 2.1610229906876555e-05

Метод скалярных произведений:
    Количество итераций: 3
    |lambdaAcc - lambda|: 1.3406487585410076e-05



Погрешность: 0.0001
Степенной метод:
    Количество итераций: 7
    |lambdaAcc - lambda|: 2.8757273158319663e-06

Метод скалярных произведений:
    Количество итераций: 4
    |lambdaAcc - lambda|: 2.374147907158175e-07



Погрешность: 1e-0

### Вывод данных (Матрица Гильберта шестого порядка)

In [29]:
print("Матрица Гильберта шестого порядка:")
print(*matrixHilbert6, sep='\n')
print()
lambdaAcc = max(abs(np.linalg.eig(matrixHilbert6)[0]))
for eps in (1e-2, 1e-3, 1e-4, 1e-5):
    print("Погрешность:", eps)
    print("Степенной метод:")
    print("    Количество итераций:", powerMethod(matrixHilbert6, eps)[1])
    print("    |lambdaAcc - lambda|:", abs(lambdaAcc - abs(powerMethod(matrixHilbert6, eps)[0])))
    print()
    print("Метод скалярных произведений:")
    print("    Количество итераций:", scalMethod(A, eps)[1])
    print("    |lambdaAcc - lambda|:", abs(lambdaAcc - abs(scalMethod(matrixHilbert6, eps)[0])))
    print()
    print()
    print()

Матрица Гильберта шестого порядка:
[1.         0.5        0.33333333 0.25       0.2        0.16666667]
[0.5        0.33333333 0.25       0.2        0.16666667 0.14285714]
[0.33333333 0.25       0.2        0.16666667 0.14285714 0.125     ]
[0.25       0.2        0.16666667 0.14285714 0.125      0.11111111]
[0.2        0.16666667 0.14285714 0.125      0.11111111 0.1       ]
[0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909]

Погрешность: 0.01
Степенной метод:
    Количество итераций: 5
    |lambdaAcc - lambda|: 0.0002936458774360773

Метод скалярных произведений:
    Количество итераций: 3
    |lambdaAcc - lambda|: 2.7699432503913712e-05



Погрешность: 0.001
Степенной метод:
    Количество итераций: 6
    |lambdaAcc - lambda|: 4.395301903570292e-05

Метод скалярных произведений:
    Количество итераций: 3
    |lambdaAcc - lambda|: 6.208181393407841e-07



Погрешность: 0.0001
Степенной метод:
    Количество итераций: 7
    |lambdaAcc - lambda|: 6.579903279346766e-06

Мет